const configuracion = {
    PUERTO: 3000,
    BASE_DATOS: { // Datos de conexion a la base de datos
        SERVIDOR: 'localhost',
        NOMBRE: 'prueba',
        USUARIO: 'root',
        CONTRASENA: null
    },
    SINCRONIZACION: true, // Indica si se eliminan las tablas para volverlas a crear.
    MODELO: {
        PAIS: 'pais',
        CONFIGURACION: 'configuracion',
        CONFIGURACION_SISTEMA: 'configuracionSistema',
        CREADOR: 'creador',
        CRONOLOGIA: 'cronologia',
        EPISODIO: 'episodio',
        EPISODIO_FANSUBS: 'episodioFansubs',
        FANSUB: 'fansub',
        GENERO: 'genero',
        SAGA: 'saga',
        SAGA_EPISODIOS: 'sagaEpisodios',
        SERIE: 'serie',
        SERIE_CREADORES: 'serieCreadores',
        SERIE_GENEROS: 'serieGeneros',
        SERIE_SAGAS: 'serieSagas',
        SERIE_TEMAS: 'serieTemas',
        SERIE_TITULOS: 'serieTitulos',
        TEMA: 'tema',
    },
    TABLAS: {
        PAIS: 'pais',
        CONFIGURACION: 'configuracion',
        CONFIGURACION_SISTEMA: 'configuracion_sistema',
        CREADOR: 'creador',
        CRONOLOGIA: 'cronologia',
        EPISODIO: 'episodio',
        EPISODIO_FANSUBS: 'episodio_fansubs',
        FANSUB: 'fansub',
        GENERO: 'genero',
        SAGA: 'saga',
        SAGA_EPISODIOS: 'saga_episodios',
        SERIE: 'serie',
        SERIE_CREADORES: 'serie_creadores',
        SERIE_GENEROS: 'serie_generos',
        SERIE_SAGAS: 'serie_sagas',
        SERIE_TEMAS: 'serie_temas',
        SERIE_TITULOS: 'serie_titulos',
        TEMA: 'tema',
    },
    RELACIONES: {
        CRONOLOGIA: 'cronologia',
        CRONOLOGIA_SERIE: 'cronologiaSerie',
        EPISODIO_FANSUBS: 'fansubs',
        EPISODIO_FANSUBS_TABLA: 'serie_fansubs',
        SAGA_EPISODIOS: 'episodios',
        SAGA_EPISODIOS_TABLA: 'saga_episodios',
        SERIE_CREADORES: 'creadores',
        SERIE_CREADORES_TABLA: 'serie_creadores',
        SERIE_GENEROS: 'generos',
        SERIE_GENEROS_TABLA: 'serie_generos',
        SERIE_PAIS: 'pais',
        SERIE_SAGAS: 'sagas',
        SERIE_SAGAS_TABLA: 'serie_sagas',
        SERIE_TEMAS: 'temas',
        SERIE_TEMAS_TABLA: 'serie_temas',
        TITULO_PAIS: 'pais',
        TITULO_SERIE: 'serie'
    },
    PROTOTIPOS: { // Prototipos de tipo de datos
        UUID: 36,
        CADENA_CH: 50,
        CADENA_MED: 100,
        CADENA_GDE: 255,
        CRC: 8
    }
}
module.exports = configuracion;